# About Scikit-Learn (sklearn)

This notebook demonstrates  some of the most useful functions of the beautiful Scikit-Learn library.

Topics:

0. An end-to-end Scikit-Learn workflow
1. Getting the data ready
2. Choose the right estimator/algorithm for our problem's
3. Fit the model/algorithm and use it to make precdictions on our data
4. Evaluting a model
5. Save and load a trained model
6. Putting it all together!

In [1]:
import numpy as np

# 0. An end-to-end Scikit-Learn workflow

In [2]:
# 1. Get the data ready
import pandas as pd
heart_disease = pd.read_csv("data/heart-disease.csv")
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [3]:
# Create x (features matrix)
x = heart_disease.drop("target", axis=1)

# Create y (labels)
y = heart_disease["target"]

In [4]:
# 2. Choose the right model and hyperparameters
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)  # create model

# We'll keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [5]:
# 3. Fit the model to the training data
from sklearn.model_selection import train_test_split

# X = features, y = labels
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [6]:
clf.fit(x_train, y_train) # train model

RandomForestClassifier()

In [7]:
x_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
257,50,1,0,144,200,0,0,126,1,0.9,1,0,3
180,55,1,0,132,353,0,1,132,1,1.2,1,1,3
23,61,1,2,150,243,1,1,137,1,1.0,1,0,2
69,62,0,0,124,209,0,1,163,0,0.0,2,0,2
256,58,1,0,128,259,0,0,130,1,3.0,1,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,34,0,1,118,210,0,1,192,0,0.7,2,0,2
123,54,0,2,108,267,0,0,167,0,0.0,2,0,2
141,43,1,0,115,303,0,1,181,0,1.2,1,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
245,48,1,0,124,274,0,0,166,0,0.5,1,0,3

In [8]:
# make a prediction
# Throw error
y_label = clf.predict(np.array([0, 2, 3, 4]))

C:\Users\win\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

ValueError: Expected 2D array, got 1D array instead:
array=[0. 2. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [9]:
y_preds = clf.predict(x_test)  # predict test data
y_preds

array([1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1])

In [10]:
y_test

64     1
60     1
210    0
18     1
177    0
      ..
82     1
174    0
96     1
266    0
79     1
Name: target, Length: 61, dtype: int64

In [11]:
# 4.Evaluate the model on the training data and test data
clf.score(x_train, y_train)

1.0

In [12]:
clf.score(x_test, y_test)

0.8524590163934426

In [13]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score